openapi: 3.1.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: http://localhost:4080
  - url: http://localhost:6001
paths:
  /ping:
    get:
      summary: pings
      responses:
        "200":
          description: ping
  /publish/baseData:
    post:
      summary: Publishes raw minute aggregate data
      responses:
        "200":
          description: Publish successful