version: '3.8'

services:
  basic-aggregate-publisher-solo:
    image: localhost/a-trade-microservice-base:latest
    container_name: a-trade-microservice-basic-aggregate-publisher
    ports:
      - "4080:8080"
    volumes:
      - ./build/libs/a-trade-microservice-basic-aggregate-publisher-0.0.1-plain.jar:/app/plugins/plugin.jar:z
      - ./data:/app/data:z